name: Add Meme to Push

on:
  push:
    branches:
      - main

jobs:
  add-meme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Add Meme to Push
        run: |
          memes=(
            "https://i.imgflip.com/4hzqe0.jpg"
            "https://i.imgflip.com/o1xox.jpg"
            "https://i.pinimg.com/736x/96/6c/fd/966cfdaa3b9e34dafa5b4636d0681e58.jpg"
            "https://th.bing.com/th/id/OIP.zfZ2U887Euo7GUEoj0W-igHaE2?pid=ImgDet&rs=1"
            "https://i.imgflip.com/1mhr8r.jpg"
          )

          random_index=$(( RANDOM % ${#memes[@]} ))
          meme_url=${memes[$random_index]}

          echo "![Meme]($meme_url)" >> README.md

      - name: Commit and Push Changes
        run: |
          git config --local user.email "j.ansul@iitg.ac.in"
          git config --local user.name "ANSULJAIN"

          git add README.md
          git commit -m "Add meme to push"
          git push origin HEAD:main
